export const LOGIN_START = 'AUTH_LOGIN_START';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const LOGIN_LOGOUT = 'AUTH_LOGOUT';
export const TOKEN_CHECKED = 'TOKEN_CHECKED';

//all constants for units actions
export const SET_UNITS = 'SET_UNITS';
export const SET_UNITS_LOADING = 'SET_UNITS_LOADING';
export const ADD_UNIT = 'ADD_UNIT';
export const SET_UNIT = 'SET_UNIT';
export const SET_UNIT_LOADING = 'SET_UNIT_LOADING';
export const EDIT_UNIT = 'EDIT_UNIT';

//all constants for users actions
export const SET_USERS = 'SET_USERS';
export const SET_USERS_LOADING = 'SET_USERS_LOADING';
export const ADD_USER = 'ADD_USER';
export const SET_USER = 'SET_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const EDIT_USER = 'EDIT_USER';
export const SET_USER_EMAIL_ERROR = 'SET_USER_EMAIL_ERROR';

//all constants for companies actions
export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_TASK_COMPANIES = 'SET_TASK_COMPANIES';
export const SET_COMPANIES_LOADING = 'SET_COMPANIES_LOADING';
export const ADD_COMPANY = 'ADD_COMPANY';
export const SET_COMPANY = 'SET_COMPANY';
export const SET_COMPANY_LOADING = 'SET_COMPANY_LOADING';
export const EDIT_COMPANY = 'EDIT_COMPANY';

//all constants for user roles actions
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const SET_USER_ROLES_LOADING = 'SET_USER_ROLES_LOADING';
export const ADD_USER_ROLE = 'ADD_USER_ROLE';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_ROLE_LOADING = 'SET_USER_ROLE_LOADING';
export const EDIT_USER_ROLE = 'EDIT_USER_ROLE';

//all constants for smtps actions
export const SET_SMTPS = 'SET_SMTPS';
export const SET_SMTPS_LOADING = 'SET_SMTPS_LOADING';
export const ADD_SMTP = 'ADD_SMTP';
export const SET_SMTP = 'SET_SMTP';
export const SET_SMTP_LOADING = 'SET_SMTP_LOADING';
export const EDIT_SMTP = 'EDIT_SMTP';

//all constants for IMAPS actions
export const SET_IMAPS = 'SET_IMAPS';
export const SET_IMAPS_LOADING = 'SET_IMAPS_LOADING';
export const ADD_IMAP = 'ADD_IMAP';
export const SET_IMAP = 'SET_IMAP';
export const SET_IMAP_LOADING = 'SET_IMAP_LOADING';
export const EDIT_IMAP = 'EDIT_IMAP';
export const DELETE_IMAP = 'DELETE_IMAP';

//all constants for PROJECTS actions
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_PROJECTS_LOADING = 'SET_PROJECTS_LOADING';
export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_PROJECT_LOADING = 'SET_PROJECT_LOADING';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const SET_PERMISSIONS_SAVED = 'SET_PERMISSIONS_SAVED';

//all constants for STATUSES actions
export const SET_STATUSES = 'SET_STATUSES';
export const SET_TASK_STATUSES = 'SET_TASK_STATUSES';
export const SET_STATUSES_LOADING = 'SET_STATUSES_LOADING';
export const ADD_STATUS = 'ADD_STATUS';
export const SET_STATUS = 'SET_STATUS';
export const SET_STATUS_LOADING = 'SET_STATUS_LOADING';
export const EDIT_STATUS = 'EDIT_STATUS';
export const DELETE_STATUS = 'DELETE_STATUS';


//all constants for COMPANY_ATTRIBUTES actions
export const SET_COMPANY_ATTRIBUTES = 'SET_COMPANY_ATTRIBUTES';
export const SET_COMPANY_ATTRIBUTES_LOADING = 'SET_COMPANY_ATTRIBUTES_LOADING';
export const ADD_COMPANY_ATTRIBUTE = 'ADD_COMPANY_ATTRIBUTE';
export const SET_COMPANY_ATTRIBUTE = 'SET_COMPANY_ATTRIBUTE';
export const SET_COMPANY_ATTRIBUTE_LOADING = 'SET_COMPANY_ATTRIBUTE_LOADING';
export const EDIT_COMPANY_ATTRIBUTE = 'EDIT_COMPANY_ATTRIBUTE';

//all constants for SIDEBAR actions
export const SET_SIDEBAR = 'SET_SIDEBAR';
export const UPDATE_SIDEBAR = 'UPDATE_SIDEBAR';

//all constants for TASK_ATTRIBUTES actions
export const SET_TASK_ATTRIBUTES = 'SET_TASK_ATTRIBUTES';
export const SET_TASK_ATTRIBUTES_LOADING = 'SET_TASK_ATTRIBUTES_LOADING';
export const ADD_TASK_ATTRIBUTE = 'ADD_TASK_ATTRIBUTE';
export const SET_TASK_ATTRIBUTE = 'SET_TASK_ATTRIBUTE';
export const SET_TASK_ATTRIBUTE_LOADING = 'SET_TASK_ATTRIBUTE_LOADING';
export const EDIT_TASK_ATTRIBUTE = 'EDIT_TASK_ATTRIBUTE';

//all constants for TAGS actions
export const SET_TAGS = 'SET_TAGS';
export const SET_TAGS_LOADING = 'SET_TAGS_LOADING';
export const ADD_TAG = 'ADD_TAG';
export const SET_TAG = 'SET_TAG';
export const SET_TAG_LOADING = 'SET_TAG_LOADING';
export const EDIT_TAG = 'EDIT_TAG';
export const DELETE_TAG = 'DELETE_TAG';

//all constants for TASKS actions
export const SET_TASKS = 'SET_TASKS';
export const SET_TASKS_LOADING = 'SET_TASKS_LOADING';
export const SET_PROJECT_TASKS_LOADING = 'SET_PROJECT_TASKS_LOADING';
export const SET_FILTER_TASKS_LOADING = 'SET_FILTER_TASKS_LOADING';
export const ADD_TASK = 'ADD_TASK';
export const CLEAR_TASK = 'CLEAR_TASK';
export const SET_TASK = 'SET_TASK';
export const SET_TASK_LOADING = 'SET_TASK_LOADING';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_FILTER_LINKS = 'SET_FILTER_LINKS';
export const SET_PROJECT_LINKS = 'SET_PROJECT_LINKS';
export const SET_TAG_TASKS_LOADING = 'SET_TAG_TASKS_LOADING';
export const SET_TAG_LINKS = 'SET_TAG_LINKS';
export const SET_TASK_ID = 'SET_TASK_ID';
export const DELETE_TASK = 'DELETE_TASK';

export const SET_FILTER_BODY = 'SET_FILTER_BODY';
export const ADD_TO_FILTER_BODY = 'ADD_TO_FILTER_BODY';

export const SET_TASK_PROJECTS = 'SET_TASK_PROJECTS';
export const SET_TASK_PROJECTS_LOADING = 'SET_TASK_PROJECTS_LOADING';
export const SET_TASKS_ATTRIBUTES = 'SET_TASKS_ATTRIBUTES';
export const SET_TASKS_ATTRIBUTES_LOADING = 'SET_TASKS_ATTRIBUTES_LOADING';
export const SET_TASK_SOLVERS = 'SET_TASK_SOLVERS';
export const DELETE_TASK_SOLVERS = 'DELETE_TASK_SOLVERS';
export const SET_TRIPOD = 'SET_TRIPOD';
export const SET_COLUMNS = 'SET_COLUMNS';

export const SET_REPEAT = 'SET_REPEAT';
export const SET_REPEAT_LOADING = 'SET_REPEAT_LOADING';

//all constants for ATTACHMENTS actions
export const ADD_ATTACHMENT = 'ADD_ATTACHMENT';
export const EDIT_ATTACHMENT = 'EDIT_ATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
export const CLEAR_ATTACHMENTS = 'CLEAR_ATTACHMENTS';

//all constants for SUBTASKS actions
export const SET_SUBTASKS = 'SET_SUBTASKS';
export const SET_SUBTASKS_LOADING = 'SET_SUBTASKS_LOADING';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const EDIT_SUBTASK = 'EDIT_SUBTASK';
export const DELETE_SUBTASK = 'DELETE_SUBTASK';

//all constants for ITEMS actions
export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEMS_LOADING = 'SET_ITEMS_LOADING';
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

//all constants for COMMENTS actions
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const ADD_COMMENT_AVATAR_URL = 'ADD_COMMENT_AVATAR_URL';
export const DELETE_COMMENT = 'DELETE_COMMENT';

//all constants for COMMENTS ATTACHMENTS actions
export const SET_COMMENT_ATTACHMENTS = 'SET_COMMENT_ATTACHMENTS';
export const SET_COMMENT_ATTACHMENT = 'SET_COMMENT_ATTACHMENT';
export const ADD_COMMENT_ATTACHMENT = 'ADD_COMMENT_ATTACHMENT';
export const SET_COMMENT_ATTACHMENTS_LOADING = 'SET_COMMENT_ATTACHMENTS_LOADING';
export const DELETE_COMMENT_ATTACHMENT = 'DELETE_COMMENT_ATTACHMENT';
export const DELETE_COMMENT_ATTACHMENTS = 'DELETE_COMMENT_ATTACHMENTS';

//all constants for FOLLOWERS actions
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWERS_LOADING = 'SET_FOLLOWERS_LOADING';
export const ADD_FOLLOWER = 'ADD_FOLLOWER';
export const DELETE_FOLLOWER = 'DELETE_FOLLOWER';

//all constants for ERROR actions
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const SET_ACTIVE_REQUESTS = 'SET_ACTIVE_REQUESTS';
export const LOWER_ACTIVE_REQUESTS = 'LOWER_ACTIVE_REQUESTS';
export const ADD_ACTIVE_REQUESTS = 'ADD_ACTIVE_REQUESTS';

//all constants for FILTER actions
export const CLEAR_FILTER_TASKS = 'CLEAR_FILTER_TASKS';
export const SET_FILTERED_TASKS = 'SET_FILTERED_TASKS';
export const SET_FILTER = 'SET_FILTER';
export const SET_FILTER_PAGE = 'SET_FILTER_PAGE';
export const SET_SHOW_FILTER = 'SET_SHOW_FILTER';
export const SET_FILTER_LOADING = 'SET_FILTER_LOADING';
export const SET_FILTER_ORDER = 'SET_FILTER_ORDER';
export const SET_UPDATE_AT = 'SET_UPDATE_AT';

//all constants for MESSAGES actions
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_MESSAGES_READ = 'SET_MESSAGES_READ';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const SET_TOP_MESSAGES = 'SET_TOP_MESSAGES';
export const START_MESSAGES_LOADING = 'START_MESSAGES_LOADING';
